/*
 * ConfigurationMacro.h
 *
 *  Created on: Jul. 26, 2020
 *      Author: Jaroslav Bosak
 */

#ifndef CONFIGURATIONMACRO_H_
#define CONFIGURATIONMACRO_H_

// Macro which will start the definition of a configuration file.
#define CONFIGURATION(Config) \
	class Config: public corm::BaseConfiguration { \
	public: \
		Config(corm::BeanManager* manager): BaseConfiguration(manager) {}

// Macro which allows for short handing the creation/definition of resources
#define RESOURCE(Type, Name) Type Name = beanManager->getBean<Type>(#Name);
// Macro which allows for short handing the registration of resources within the ConfigurationWrapper
#define CONFIG_WRAPPER_REGISTER_RESOURCE(Type, Name) registerResource(#Name);

// Macro which provides the declaration of the ConfigurationWrapper registerResources method
#define CONFIGURATION_WRAPPER_REGISTER_RESOURCES_DECL(Config) \
template<> \
void corm::ConfigurationWrapper<Config>::registerResources() { \
	configName = #Config;

/*
 * Macro which ends the definition of a configuration file (and finalized the ConfigurationWrapper without any
 * registered resources), for situations where there is a configuration file that does not require any resources.
 */
#define CONFIGURATION_END_NO_RESOURCE(Config) \
}; \
CONFIGURATION_WRAPPER_REGISTER_RESOURCES_DECL(Config) \
}

// Macros which act together to determine how many resources are desired (i.e.: how large the __VA_ARGS__ is)
#define VA_NUM_ARGS(...) VA_NUM_ARGS_IMPL(__VA_ARGS__, \
	256, 255, 254, 253, 252, 251, 250, 249, 248, 247, 246, 245, 244, 243, 242, 241, 240, 239, 238, 237, \
	236, 235, 234, 233, 232, 231, 230, 229, 228, 227, 226, 225, 224, 223, 222, 221, 220, 219, 218, 217, \
	216, 215, 214, 213, 212, 211, 210, 209, 208, 207, 206, 205, 204, 203, 202, 201, 200, 199, 198, 197, \
	196, 195, 194, 193, 192, 191, 190, 189, 188, 187, 186, 185, 184, 183, 182, 181, 180, 179, 178, 177, \
	176, 175, 174, 173, 172, 171, 170, 169, 168, 167, 166, 165, 164, 163, 162, 161, 160, 159, 158, 157, \
	156, 155, 154, 153, 152, 151, 150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138, 137, \
	136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125, 124, 123, 122, 121, 120, 119, 118, 117, \
	116, 115, 114, 113, 112, 111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100, 99, 98, 97, \
	96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, \
	76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, \
	56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, \
	36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, \
	16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1)
#define VA_NUM_ARGS_IMPL( \
	_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, \
	_21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, \
	_41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, _56, _57, _58, _59, _60, \
	_61, _62, _63, _64, _65, _66, _67, _68, _69, _70, _71, _72, _73, _74, _75, _76, _77, _78, _79, _80, \
	_81, _82, _83, _84, _85, _86, _87, _88, _89, _90, _91, _92, _93, _94, _95, _96, _97, _98, _99, _100, \
	_101, _102, _103, _104, _105, _106, _107, _108, _109, _110, _111, _112, _113, _114, _115, _116, _117, _118, _119, _120, \
	_121, _122, _123, _124, _125, _126, _127, _128, _129, _130, _131, _132, _133, _134, _135, _136, _137, _138, _139, _140, \
	_141, _142, _143, _144, _145, _146, _147, _148, _149, _150, _151, _152, _153, _154, _155, _156, _157, _158, _159, _160, \
	_161, _162, _163, _164, _165, _166, _167, _168, _169, _170, _171, _172, _173, _174, _175, _176, _177, _178, _179, _180, \
	_181, _182, _183, _184, _185, _186, _187, _188, _189, _190, _191, _192, _193, _194, _195, _196, _197, _198, _199, _200, \
	_201, _202, _203, _204, _205, _206, _207, _208, _209, _210, _211, _212, _213, _214, _215, _216, _217, _218, _219, _220, \
	_221, _222, _223, _224, _225, _226, _227, _228, _229, _230, _231, _232, _233, _234, _235, _236, _237, _238, _239, _240, \
	_241, _242, _243, _244, _245, _246, _247, _248, _249, _250, _251, _252, _253, _254, _255, _256, N,...) N

// Helper macros to determine where to start processing the iterative generation macros based on the size of the input
#define macro_dispatcher(func, ...) \
            macro_dispatcher_(func, VA_NUM_ARGS(__VA_ARGS__))
#define macro_dispatcher_(func, nargs) \
            macro_dispatcher__(func, nargs)
#define macro_dispatcher__(func, nargs) \
            func##nargs

// Iterative Macros for generating the resource in the configuration class
#define CONFIG_RESOURCE1(P) RESOURCE P
#define CONFIG_RESOURCE2(P, ...) RESOURCE P \
	CONFIG_RESOURCE1(__VA_ARGS__)
#define CONFIG_RESOURCE3(P, ...) RESOURCE P \
	CONFIG_RESOURCE2(__VA_ARGS__)
#define CONFIG_RESOURCE4(P, ...) RESOURCE P \
	CONFIG_RESOURCE3(__VA_ARGS__)
#define CONFIG_RESOURCE5(P, ...) RESOURCE P \
	CONFIG_RESOURCE4(__VA_ARGS__)
#define CONFIG_RESOURCE6(P, ...) RESOURCE P \
	CONFIG_RESOURCE5(__VA_ARGS__)
#define CONFIG_RESOURCE7(P, ...) RESOURCE P \
	CONFIG_RESOURCE6(__VA_ARGS__)
#define CONFIG_RESOURCE8(P, ...) RESOURCE P \
	CONFIG_RESOURCE7(__VA_ARGS__)
#define CONFIG_RESOURCE9(P, ...) RESOURCE P \
	CONFIG_RESOURCE8(__VA_ARGS__)
#define CONFIG_RESOURCE10(P, ...) RESOURCE P \
	CONFIG_RESOURCE9(__VA_ARGS__)
#define CONFIG_RESOURCE11(P, ...) RESOURCE P \
	CONFIG_RESOURCE10(__VA_ARGS__)
#define CONFIG_RESOURCE12(P, ...) RESOURCE P \
	CONFIG_RESOURCE11(__VA_ARGS__)
#define CONFIG_RESOURCE13(P, ...) RESOURCE P \
	CONFIG_RESOURCE12(__VA_ARGS__)
#define CONFIG_RESOURCE14(P, ...) RESOURCE P \
	CONFIG_RESOURCE13(__VA_ARGS__)
#define CONFIG_RESOURCE15(P, ...) RESOURCE P \
	CONFIG_RESOURCE14(__VA_ARGS__)
#define CONFIG_RESOURCE16(P, ...) RESOURCE P \
	CONFIG_RESOURCE15(__VA_ARGS__)
#define CONFIG_RESOURCE17(P, ...) RESOURCE P \
	CONFIG_RESOURCE16(__VA_ARGS__)
#define CONFIG_RESOURCE18(P, ...) RESOURCE P \
	CONFIG_RESOURCE17(__VA_ARGS__)
#define CONFIG_RESOURCE19(P, ...) RESOURCE P \
	CONFIG_RESOURCE18(__VA_ARGS__)
#define CONFIG_RESOURCE20(P, ...) RESOURCE P \
	CONFIG_RESOURCE19(__VA_ARGS__)
#define CONFIG_RESOURCE21(P, ...) RESOURCE P \
	CONFIG_RESOURCE20(__VA_ARGS__)
#define CONFIG_RESOURCE22(P, ...) RESOURCE P \
	CONFIG_RESOURCE21(__VA_ARGS__)
#define CONFIG_RESOURCE23(P, ...) RESOURCE P \
	CONFIG_RESOURCE22(__VA_ARGS__)
#define CONFIG_RESOURCE24(P, ...) RESOURCE P \
	CONFIG_RESOURCE23(__VA_ARGS__)
#define CONFIG_RESOURCE25(P, ...) RESOURCE P \
	CONFIG_RESOURCE24(__VA_ARGS__)
#define CONFIG_RESOURCE26(P, ...) RESOURCE P \
	CONFIG_RESOURCE25(__VA_ARGS__)
#define CONFIG_RESOURCE27(P, ...) RESOURCE P \
	CONFIG_RESOURCE26(__VA_ARGS__)
#define CONFIG_RESOURCE28(P, ...) RESOURCE P \
	CONFIG_RESOURCE27(__VA_ARGS__)
#define CONFIG_RESOURCE29(P, ...) RESOURCE P \
	CONFIG_RESOURCE28(__VA_ARGS__)
#define CONFIG_RESOURCE30(P, ...) RESOURCE P \
	CONFIG_RESOURCE29(__VA_ARGS__)
#define CONFIG_RESOURCE31(P, ...) RESOURCE P \
	CONFIG_RESOURCE30(__VA_ARGS__)
#define CONFIG_RESOURCE32(P, ...) RESOURCE P \
	CONFIG_RESOURCE31(__VA_ARGS__)
#define CONFIG_RESOURCE33(P, ...) RESOURCE P \
	CONFIG_RESOURCE32(__VA_ARGS__)
#define CONFIG_RESOURCE34(P, ...) RESOURCE P \
	CONFIG_RESOURCE33(__VA_ARGS__)
#define CONFIG_RESOURCE35(P, ...) RESOURCE P \
	CONFIG_RESOURCE34(__VA_ARGS__)
#define CONFIG_RESOURCE36(P, ...) RESOURCE P \
	CONFIG_RESOURCE35(__VA_ARGS__)
#define CONFIG_RESOURCE37(P, ...) RESOURCE P \
	CONFIG_RESOURCE36(__VA_ARGS__)
#define CONFIG_RESOURCE38(P, ...) RESOURCE P \
	CONFIG_RESOURCE37(__VA_ARGS__)
#define CONFIG_RESOURCE39(P, ...) RESOURCE P \
	CONFIG_RESOURCE38(__VA_ARGS__)
#define CONFIG_RESOURCE40(P, ...) RESOURCE P \
	CONFIG_RESOURCE39(__VA_ARGS__)
#define CONFIG_RESOURCE41(P, ...) RESOURCE P \
	CONFIG_RESOURCE40(__VA_ARGS__)
#define CONFIG_RESOURCE42(P, ...) RESOURCE P \
	CONFIG_RESOURCE41(__VA_ARGS__)
#define CONFIG_RESOURCE43(P, ...) RESOURCE P \
	CONFIG_RESOURCE42(__VA_ARGS__)
#define CONFIG_RESOURCE44(P, ...) RESOURCE P \
	CONFIG_RESOURCE43(__VA_ARGS__)
#define CONFIG_RESOURCE45(P, ...) RESOURCE P \
	CONFIG_RESOURCE44(__VA_ARGS__)
#define CONFIG_RESOURCE46(P, ...) RESOURCE P \
	CONFIG_RESOURCE45(__VA_ARGS__)
#define CONFIG_RESOURCE47(P, ...) RESOURCE P \
	CONFIG_RESOURCE46(__VA_ARGS__)
#define CONFIG_RESOURCE48(P, ...) RESOURCE P \
	CONFIG_RESOURCE47(__VA_ARGS__)
#define CONFIG_RESOURCE49(P, ...) RESOURCE P \
	CONFIG_RESOURCE48(__VA_ARGS__)
#define CONFIG_RESOURCE50(P, ...) RESOURCE P \
	CONFIG_RESOURCE49(__VA_ARGS__)
#define CONFIG_RESOURCE51(P, ...) RESOURCE P \
	CONFIG_RESOURCE50(__VA_ARGS__)
#define CONFIG_RESOURCE52(P, ...) RESOURCE P \
	CONFIG_RESOURCE51(__VA_ARGS__)
#define CONFIG_RESOURCE53(P, ...) RESOURCE P \
	CONFIG_RESOURCE52(__VA_ARGS__)
#define CONFIG_RESOURCE54(P, ...) RESOURCE P \
	CONFIG_RESOURCE53(__VA_ARGS__)
#define CONFIG_RESOURCE55(P, ...) RESOURCE P \
	CONFIG_RESOURCE54(__VA_ARGS__)
#define CONFIG_RESOURCE56(P, ...) RESOURCE P \
	CONFIG_RESOURCE55(__VA_ARGS__)
#define CONFIG_RESOURCE57(P, ...) RESOURCE P \
	CONFIG_RESOURCE56(__VA_ARGS__)
#define CONFIG_RESOURCE58(P, ...) RESOURCE P \
	CONFIG_RESOURCE57(__VA_ARGS__)
#define CONFIG_RESOURCE59(P, ...) RESOURCE P \
	CONFIG_RESOURCE58(__VA_ARGS__)
#define CONFIG_RESOURCE60(P, ...) RESOURCE P \
	CONFIG_RESOURCE59(__VA_ARGS__)
#define CONFIG_RESOURCE61(P, ...) RESOURCE P \
	CONFIG_RESOURCE60(__VA_ARGS__)
#define CONFIG_RESOURCE62(P, ...) RESOURCE P \
	CONFIG_RESOURCE61(__VA_ARGS__)
#define CONFIG_RESOURCE63(P, ...) RESOURCE P \
	CONFIG_RESOURCE62(__VA_ARGS__)
#define CONFIG_RESOURCE64(P, ...) RESOURCE P \
	CONFIG_RESOURCE63(__VA_ARGS__)
#define CONFIG_RESOURCE65(P, ...) RESOURCE P \
	CONFIG_RESOURCE64(__VA_ARGS__)
#define CONFIG_RESOURCE66(P, ...) RESOURCE P \
	CONFIG_RESOURCE65(__VA_ARGS__)
#define CONFIG_RESOURCE67(P, ...) RESOURCE P \
	CONFIG_RESOURCE66(__VA_ARGS__)
#define CONFIG_RESOURCE68(P, ...) RESOURCE P \
	CONFIG_RESOURCE67(__VA_ARGS__)
#define CONFIG_RESOURCE69(P, ...) RESOURCE P \
	CONFIG_RESOURCE68(__VA_ARGS__)
#define CONFIG_RESOURCE70(P, ...) RESOURCE P \
	CONFIG_RESOURCE69(__VA_ARGS__)
#define CONFIG_RESOURCE71(P, ...) RESOURCE P \
	CONFIG_RESOURCE70(__VA_ARGS__)
#define CONFIG_RESOURCE72(P, ...) RESOURCE P \
	CONFIG_RESOURCE71(__VA_ARGS__)
#define CONFIG_RESOURCE73(P, ...) RESOURCE P \
	CONFIG_RESOURCE72(__VA_ARGS__)
#define CONFIG_RESOURCE74(P, ...) RESOURCE P \
	CONFIG_RESOURCE73(__VA_ARGS__)
#define CONFIG_RESOURCE75(P, ...) RESOURCE P \
	CONFIG_RESOURCE74(__VA_ARGS__)
#define CONFIG_RESOURCE76(P, ...) RESOURCE P \
	CONFIG_RESOURCE75(__VA_ARGS__)
#define CONFIG_RESOURCE77(P, ...) RESOURCE P \
	CONFIG_RESOURCE76(__VA_ARGS__)
#define CONFIG_RESOURCE78(P, ...) RESOURCE P \
	CONFIG_RESOURCE77(__VA_ARGS__)
#define CONFIG_RESOURCE79(P, ...) RESOURCE P \
	CONFIG_RESOURCE78(__VA_ARGS__)
#define CONFIG_RESOURCE80(P, ...) RESOURCE P \
	CONFIG_RESOURCE79(__VA_ARGS__)
#define CONFIG_RESOURCE81(P, ...) RESOURCE P \
	CONFIG_RESOURCE80(__VA_ARGS__)
#define CONFIG_RESOURCE82(P, ...) RESOURCE P \
	CONFIG_RESOURCE81(__VA_ARGS__)
#define CONFIG_RESOURCE83(P, ...) RESOURCE P \
	CONFIG_RESOURCE82(__VA_ARGS__)
#define CONFIG_RESOURCE84(P, ...) RESOURCE P \
	CONFIG_RESOURCE83(__VA_ARGS__)
#define CONFIG_RESOURCE85(P, ...) RESOURCE P \
	CONFIG_RESOURCE84(__VA_ARGS__)
#define CONFIG_RESOURCE86(P, ...) RESOURCE P \
	CONFIG_RESOURCE85(__VA_ARGS__)
#define CONFIG_RESOURCE87(P, ...) RESOURCE P \
	CONFIG_RESOURCE86(__VA_ARGS__)
#define CONFIG_RESOURCE88(P, ...) RESOURCE P \
	CONFIG_RESOURCE87(__VA_ARGS__)
#define CONFIG_RESOURCE89(P, ...) RESOURCE P \
	CONFIG_RESOURCE88(__VA_ARGS__)
#define CONFIG_RESOURCE90(P, ...) RESOURCE P \
	CONFIG_RESOURCE89(__VA_ARGS__)
#define CONFIG_RESOURCE91(P, ...) RESOURCE P \
	CONFIG_RESOURCE90(__VA_ARGS__)
#define CONFIG_RESOURCE92(P, ...) RESOURCE P \
	CONFIG_RESOURCE91(__VA_ARGS__)
#define CONFIG_RESOURCE93(P, ...) RESOURCE P \
	CONFIG_RESOURCE92(__VA_ARGS__)
#define CONFIG_RESOURCE94(P, ...) RESOURCE P \
	CONFIG_RESOURCE93(__VA_ARGS__)
#define CONFIG_RESOURCE95(P, ...) RESOURCE P \
	CONFIG_RESOURCE94(__VA_ARGS__)
#define CONFIG_RESOURCE96(P, ...) RESOURCE P \
	CONFIG_RESOURCE95(__VA_ARGS__)
#define CONFIG_RESOURCE97(P, ...) RESOURCE P \
	CONFIG_RESOURCE96(__VA_ARGS__)
#define CONFIG_RESOURCE98(P, ...) RESOURCE P \
	CONFIG_RESOURCE97(__VA_ARGS__)
#define CONFIG_RESOURCE99(P, ...) RESOURCE P \
	CONFIG_RESOURCE98(__VA_ARGS__)
#define CONFIG_RESOURCE100(P, ...) RESOURCE P \
	CONFIG_RESOURCE99(__VA_ARGS__)
#define CONFIG_RESOURCE101(P, ...) RESOURCE P \
	CONFIG_RESOURCE100(__VA_ARGS__)
#define CONFIG_RESOURCE102(P, ...) RESOURCE P \
	CONFIG_RESOURCE101(__VA_ARGS__)
#define CONFIG_RESOURCE103(P, ...) RESOURCE P \
	CONFIG_RESOURCE102(__VA_ARGS__)
#define CONFIG_RESOURCE104(P, ...) RESOURCE P \
	CONFIG_RESOURCE103(__VA_ARGS__)
#define CONFIG_RESOURCE105(P, ...) RESOURCE P \
	CONFIG_RESOURCE104(__VA_ARGS__)
#define CONFIG_RESOURCE106(P, ...) RESOURCE P \
	CONFIG_RESOURCE105(__VA_ARGS__)
#define CONFIG_RESOURCE107(P, ...) RESOURCE P \
	CONFIG_RESOURCE106(__VA_ARGS__)
#define CONFIG_RESOURCE108(P, ...) RESOURCE P \
	CONFIG_RESOURCE107(__VA_ARGS__)
#define CONFIG_RESOURCE109(P, ...) RESOURCE P \
	CONFIG_RESOURCE108(__VA_ARGS__)
#define CONFIG_RESOURCE110(P, ...) RESOURCE P \
	CONFIG_RESOURCE109(__VA_ARGS__)
#define CONFIG_RESOURCE111(P, ...) RESOURCE P \
	CONFIG_RESOURCE110(__VA_ARGS__)
#define CONFIG_RESOURCE112(P, ...) RESOURCE P \
	CONFIG_RESOURCE111(__VA_ARGS__)
#define CONFIG_RESOURCE113(P, ...) RESOURCE P \
	CONFIG_RESOURCE112(__VA_ARGS__)
#define CONFIG_RESOURCE114(P, ...) RESOURCE P \
	CONFIG_RESOURCE113(__VA_ARGS__)
#define CONFIG_RESOURCE115(P, ...) RESOURCE P \
	CONFIG_RESOURCE114(__VA_ARGS__)
#define CONFIG_RESOURCE116(P, ...) RESOURCE P \
	CONFIG_RESOURCE115(__VA_ARGS__)
#define CONFIG_RESOURCE117(P, ...) RESOURCE P \
	CONFIG_RESOURCE116(__VA_ARGS__)
#define CONFIG_RESOURCE118(P, ...) RESOURCE P \
	CONFIG_RESOURCE117(__VA_ARGS__)
#define CONFIG_RESOURCE119(P, ...) RESOURCE P \
	CONFIG_RESOURCE118(__VA_ARGS__)
#define CONFIG_RESOURCE120(P, ...) RESOURCE P \
	CONFIG_RESOURCE119(__VA_ARGS__)
#define CONFIG_RESOURCE121(P, ...) RESOURCE P \
	CONFIG_RESOURCE120(__VA_ARGS__)
#define CONFIG_RESOURCE122(P, ...) RESOURCE P \
	CONFIG_RESOURCE121(__VA_ARGS__)
#define CONFIG_RESOURCE123(P, ...) RESOURCE P \
	CONFIG_RESOURCE122(__VA_ARGS__)
#define CONFIG_RESOURCE124(P, ...) RESOURCE P \
	CONFIG_RESOURCE123(__VA_ARGS__)
#define CONFIG_RESOURCE125(P, ...) RESOURCE P \
	CONFIG_RESOURCE124(__VA_ARGS__)
#define CONFIG_RESOURCE126(P, ...) RESOURCE P \
	CONFIG_RESOURCE125(__VA_ARGS__)
#define CONFIG_RESOURCE127(P, ...) RESOURCE P \
	CONFIG_RESOURCE126(__VA_ARGS__)
#define CONFIG_RESOURCE128(P, ...) RESOURCE P \
	CONFIG_RESOURCE127(__VA_ARGS__)
#define CONFIG_RESOURCE129(P, ...) RESOURCE P \
	CONFIG_RESOURCE128(__VA_ARGS__)
#define CONFIG_RESOURCE130(P, ...) RESOURCE P \
	CONFIG_RESOURCE129(__VA_ARGS__)
#define CONFIG_RESOURCE131(P, ...) RESOURCE P \
	CONFIG_RESOURCE130(__VA_ARGS__)
#define CONFIG_RESOURCE132(P, ...) RESOURCE P \
	CONFIG_RESOURCE131(__VA_ARGS__)
#define CONFIG_RESOURCE133(P, ...) RESOURCE P \
	CONFIG_RESOURCE132(__VA_ARGS__)
#define CONFIG_RESOURCE134(P, ...) RESOURCE P \
	CONFIG_RESOURCE133(__VA_ARGS__)
#define CONFIG_RESOURCE135(P, ...) RESOURCE P \
	CONFIG_RESOURCE134(__VA_ARGS__)
#define CONFIG_RESOURCE136(P, ...) RESOURCE P \
	CONFIG_RESOURCE135(__VA_ARGS__)
#define CONFIG_RESOURCE137(P, ...) RESOURCE P \
	CONFIG_RESOURCE136(__VA_ARGS__)
#define CONFIG_RESOURCE138(P, ...) RESOURCE P \
	CONFIG_RESOURCE137(__VA_ARGS__)
#define CONFIG_RESOURCE139(P, ...) RESOURCE P \
	CONFIG_RESOURCE138(__VA_ARGS__)
#define CONFIG_RESOURCE140(P, ...) RESOURCE P \
	CONFIG_RESOURCE139(__VA_ARGS__)
#define CONFIG_RESOURCE141(P, ...) RESOURCE P \
	CONFIG_RESOURCE140(__VA_ARGS__)
#define CONFIG_RESOURCE142(P, ...) RESOURCE P \
	CONFIG_RESOURCE141(__VA_ARGS__)
#define CONFIG_RESOURCE143(P, ...) RESOURCE P \
	CONFIG_RESOURCE142(__VA_ARGS__)
#define CONFIG_RESOURCE144(P, ...) RESOURCE P \
	CONFIG_RESOURCE143(__VA_ARGS__)
#define CONFIG_RESOURCE145(P, ...) RESOURCE P \
	CONFIG_RESOURCE144(__VA_ARGS__)
#define CONFIG_RESOURCE146(P, ...) RESOURCE P \
	CONFIG_RESOURCE145(__VA_ARGS__)
#define CONFIG_RESOURCE147(P, ...) RESOURCE P \
	CONFIG_RESOURCE146(__VA_ARGS__)
#define CONFIG_RESOURCE148(P, ...) RESOURCE P \
	CONFIG_RESOURCE147(__VA_ARGS__)
#define CONFIG_RESOURCE149(P, ...) RESOURCE P \
	CONFIG_RESOURCE148(__VA_ARGS__)
#define CONFIG_RESOURCE150(P, ...) RESOURCE P \
	CONFIG_RESOURCE149(__VA_ARGS__)
#define CONFIG_RESOURCE151(P, ...) RESOURCE P \
	CONFIG_RESOURCE150(__VA_ARGS__)
#define CONFIG_RESOURCE152(P, ...) RESOURCE P \
	CONFIG_RESOURCE151(__VA_ARGS__)
#define CONFIG_RESOURCE153(P, ...) RESOURCE P \
	CONFIG_RESOURCE152(__VA_ARGS__)
#define CONFIG_RESOURCE154(P, ...) RESOURCE P \
	CONFIG_RESOURCE153(__VA_ARGS__)
#define CONFIG_RESOURCE155(P, ...) RESOURCE P \
	CONFIG_RESOURCE154(__VA_ARGS__)
#define CONFIG_RESOURCE156(P, ...) RESOURCE P \
	CONFIG_RESOURCE155(__VA_ARGS__)
#define CONFIG_RESOURCE157(P, ...) RESOURCE P \
	CONFIG_RESOURCE156(__VA_ARGS__)
#define CONFIG_RESOURCE158(P, ...) RESOURCE P \
	CONFIG_RESOURCE157(__VA_ARGS__)
#define CONFIG_RESOURCE159(P, ...) RESOURCE P \
	CONFIG_RESOURCE158(__VA_ARGS__)
#define CONFIG_RESOURCE160(P, ...) RESOURCE P \
	CONFIG_RESOURCE159(__VA_ARGS__)
#define CONFIG_RESOURCE161(P, ...) RESOURCE P \
	CONFIG_RESOURCE160(__VA_ARGS__)
#define CONFIG_RESOURCE162(P, ...) RESOURCE P \
	CONFIG_RESOURCE161(__VA_ARGS__)
#define CONFIG_RESOURCE163(P, ...) RESOURCE P \
	CONFIG_RESOURCE162(__VA_ARGS__)
#define CONFIG_RESOURCE164(P, ...) RESOURCE P \
	CONFIG_RESOURCE163(__VA_ARGS__)
#define CONFIG_RESOURCE165(P, ...) RESOURCE P \
	CONFIG_RESOURCE164(__VA_ARGS__)
#define CONFIG_RESOURCE166(P, ...) RESOURCE P \
	CONFIG_RESOURCE165(__VA_ARGS__)
#define CONFIG_RESOURCE167(P, ...) RESOURCE P \
	CONFIG_RESOURCE166(__VA_ARGS__)
#define CONFIG_RESOURCE168(P, ...) RESOURCE P \
	CONFIG_RESOURCE167(__VA_ARGS__)
#define CONFIG_RESOURCE169(P, ...) RESOURCE P \
	CONFIG_RESOURCE168(__VA_ARGS__)
#define CONFIG_RESOURCE170(P, ...) RESOURCE P \
	CONFIG_RESOURCE169(__VA_ARGS__)
#define CONFIG_RESOURCE171(P, ...) RESOURCE P \
	CONFIG_RESOURCE170(__VA_ARGS__)
#define CONFIG_RESOURCE172(P, ...) RESOURCE P \
	CONFIG_RESOURCE171(__VA_ARGS__)
#define CONFIG_RESOURCE173(P, ...) RESOURCE P \
	CONFIG_RESOURCE172(__VA_ARGS__)
#define CONFIG_RESOURCE174(P, ...) RESOURCE P \
	CONFIG_RESOURCE173(__VA_ARGS__)
#define CONFIG_RESOURCE175(P, ...) RESOURCE P \
	CONFIG_RESOURCE174(__VA_ARGS__)
#define CONFIG_RESOURCE176(P, ...) RESOURCE P \
	CONFIG_RESOURCE175(__VA_ARGS__)
#define CONFIG_RESOURCE177(P, ...) RESOURCE P \
	CONFIG_RESOURCE176(__VA_ARGS__)
#define CONFIG_RESOURCE178(P, ...) RESOURCE P \
	CONFIG_RESOURCE177(__VA_ARGS__)
#define CONFIG_RESOURCE179(P, ...) RESOURCE P \
	CONFIG_RESOURCE178(__VA_ARGS__)
#define CONFIG_RESOURCE180(P, ...) RESOURCE P \
	CONFIG_RESOURCE179(__VA_ARGS__)
#define CONFIG_RESOURCE181(P, ...) RESOURCE P \
	CONFIG_RESOURCE180(__VA_ARGS__)
#define CONFIG_RESOURCE182(P, ...) RESOURCE P \
	CONFIG_RESOURCE181(__VA_ARGS__)
#define CONFIG_RESOURCE183(P, ...) RESOURCE P \
	CONFIG_RESOURCE182(__VA_ARGS__)
#define CONFIG_RESOURCE184(P, ...) RESOURCE P \
	CONFIG_RESOURCE183(__VA_ARGS__)
#define CONFIG_RESOURCE185(P, ...) RESOURCE P \
	CONFIG_RESOURCE184(__VA_ARGS__)
#define CONFIG_RESOURCE186(P, ...) RESOURCE P \
	CONFIG_RESOURCE185(__VA_ARGS__)
#define CONFIG_RESOURCE187(P, ...) RESOURCE P \
	CONFIG_RESOURCE186(__VA_ARGS__)
#define CONFIG_RESOURCE188(P, ...) RESOURCE P \
	CONFIG_RESOURCE187(__VA_ARGS__)
#define CONFIG_RESOURCE189(P, ...) RESOURCE P \
	CONFIG_RESOURCE188(__VA_ARGS__)
#define CONFIG_RESOURCE190(P, ...) RESOURCE P \
	CONFIG_RESOURCE189(__VA_ARGS__)
#define CONFIG_RESOURCE191(P, ...) RESOURCE P \
	CONFIG_RESOURCE190(__VA_ARGS__)
#define CONFIG_RESOURCE192(P, ...) RESOURCE P \
	CONFIG_RESOURCE191(__VA_ARGS__)
#define CONFIG_RESOURCE193(P, ...) RESOURCE P \
	CONFIG_RESOURCE192(__VA_ARGS__)
#define CONFIG_RESOURCE194(P, ...) RESOURCE P \
	CONFIG_RESOURCE193(__VA_ARGS__)
#define CONFIG_RESOURCE195(P, ...) RESOURCE P \
	CONFIG_RESOURCE194(__VA_ARGS__)
#define CONFIG_RESOURCE196(P, ...) RESOURCE P \
	CONFIG_RESOURCE195(__VA_ARGS__)
#define CONFIG_RESOURCE197(P, ...) RESOURCE P \
	CONFIG_RESOURCE196(__VA_ARGS__)
#define CONFIG_RESOURCE198(P, ...) RESOURCE P \
	CONFIG_RESOURCE197(__VA_ARGS__)
#define CONFIG_RESOURCE199(P, ...) RESOURCE P \
	CONFIG_RESOURCE198(__VA_ARGS__)
#define CONFIG_RESOURCE200(P, ...) RESOURCE P \
	CONFIG_RESOURCE199(__VA_ARGS__)
#define CONFIG_RESOURCE201(P, ...) RESOURCE P \
	CONFIG_RESOURCE200(__VA_ARGS__)
#define CONFIG_RESOURCE202(P, ...) RESOURCE P \
	CONFIG_RESOURCE201(__VA_ARGS__)
#define CONFIG_RESOURCE203(P, ...) RESOURCE P \
	CONFIG_RESOURCE202(__VA_ARGS__)
#define CONFIG_RESOURCE204(P, ...) RESOURCE P \
	CONFIG_RESOURCE203(__VA_ARGS__)
#define CONFIG_RESOURCE205(P, ...) RESOURCE P \
	CONFIG_RESOURCE204(__VA_ARGS__)
#define CONFIG_RESOURCE206(P, ...) RESOURCE P \
	CONFIG_RESOURCE205(__VA_ARGS__)
#define CONFIG_RESOURCE207(P, ...) RESOURCE P \
	CONFIG_RESOURCE206(__VA_ARGS__)
#define CONFIG_RESOURCE208(P, ...) RESOURCE P \
	CONFIG_RESOURCE207(__VA_ARGS__)
#define CONFIG_RESOURCE209(P, ...) RESOURCE P \
	CONFIG_RESOURCE208(__VA_ARGS__)
#define CONFIG_RESOURCE210(P, ...) RESOURCE P \
	CONFIG_RESOURCE209(__VA_ARGS__)
#define CONFIG_RESOURCE211(P, ...) RESOURCE P \
	CONFIG_RESOURCE210(__VA_ARGS__)
#define CONFIG_RESOURCE212(P, ...) RESOURCE P \
	CONFIG_RESOURCE211(__VA_ARGS__)
#define CONFIG_RESOURCE213(P, ...) RESOURCE P \
	CONFIG_RESOURCE212(__VA_ARGS__)
#define CONFIG_RESOURCE214(P, ...) RESOURCE P \
	CONFIG_RESOURCE213(__VA_ARGS__)
#define CONFIG_RESOURCE215(P, ...) RESOURCE P \
	CONFIG_RESOURCE214(__VA_ARGS__)
#define CONFIG_RESOURCE216(P, ...) RESOURCE P \
	CONFIG_RESOURCE215(__VA_ARGS__)
#define CONFIG_RESOURCE217(P, ...) RESOURCE P \
	CONFIG_RESOURCE216(__VA_ARGS__)
#define CONFIG_RESOURCE218(P, ...) RESOURCE P \
	CONFIG_RESOURCE217(__VA_ARGS__)
#define CONFIG_RESOURCE219(P, ...) RESOURCE P \
	CONFIG_RESOURCE218(__VA_ARGS__)
#define CONFIG_RESOURCE220(P, ...) RESOURCE P \
	CONFIG_RESOURCE219(__VA_ARGS__)
#define CONFIG_RESOURCE221(P, ...) RESOURCE P \
	CONFIG_RESOURCE220(__VA_ARGS__)
#define CONFIG_RESOURCE222(P, ...) RESOURCE P \
	CONFIG_RESOURCE221(__VA_ARGS__)
#define CONFIG_RESOURCE223(P, ...) RESOURCE P \
	CONFIG_RESOURCE222(__VA_ARGS__)
#define CONFIG_RESOURCE224(P, ...) RESOURCE P \
	CONFIG_RESOURCE223(__VA_ARGS__)
#define CONFIG_RESOURCE225(P, ...) RESOURCE P \
	CONFIG_RESOURCE224(__VA_ARGS__)
#define CONFIG_RESOURCE226(P, ...) RESOURCE P \
	CONFIG_RESOURCE225(__VA_ARGS__)
#define CONFIG_RESOURCE227(P, ...) RESOURCE P \
	CONFIG_RESOURCE226(__VA_ARGS__)
#define CONFIG_RESOURCE228(P, ...) RESOURCE P \
	CONFIG_RESOURCE227(__VA_ARGS__)
#define CONFIG_RESOURCE229(P, ...) RESOURCE P \
	CONFIG_RESOURCE228(__VA_ARGS__)
#define CONFIG_RESOURCE230(P, ...) RESOURCE P \
	CONFIG_RESOURCE229(__VA_ARGS__)
#define CONFIG_RESOURCE231(P, ...) RESOURCE P \
	CONFIG_RESOURCE230(__VA_ARGS__)
#define CONFIG_RESOURCE232(P, ...) RESOURCE P \
	CONFIG_RESOURCE231(__VA_ARGS__)
#define CONFIG_RESOURCE233(P, ...) RESOURCE P \
	CONFIG_RESOURCE232(__VA_ARGS__)
#define CONFIG_RESOURCE234(P, ...) RESOURCE P \
	CONFIG_RESOURCE233(__VA_ARGS__)
#define CONFIG_RESOURCE235(P, ...) RESOURCE P \
	CONFIG_RESOURCE234(__VA_ARGS__)
#define CONFIG_RESOURCE236(P, ...) RESOURCE P \
	CONFIG_RESOURCE235(__VA_ARGS__)
#define CONFIG_RESOURCE237(P, ...) RESOURCE P \
	CONFIG_RESOURCE236(__VA_ARGS__)
#define CONFIG_RESOURCE238(P, ...) RESOURCE P \
	CONFIG_RESOURCE237(__VA_ARGS__)
#define CONFIG_RESOURCE239(P, ...) RESOURCE P \
	CONFIG_RESOURCE238(__VA_ARGS__)
#define CONFIG_RESOURCE240(P, ...) RESOURCE P \
	CONFIG_RESOURCE239(__VA_ARGS__)
#define CONFIG_RESOURCE241(P, ...) RESOURCE P \
	CONFIG_RESOURCE240(__VA_ARGS__)
#define CONFIG_RESOURCE242(P, ...) RESOURCE P \
	CONFIG_RESOURCE241(__VA_ARGS__)
#define CONFIG_RESOURCE243(P, ...) RESOURCE P \
	CONFIG_RESOURCE242(__VA_ARGS__)
#define CONFIG_RESOURCE244(P, ...) RESOURCE P \
	CONFIG_RESOURCE243(__VA_ARGS__)
#define CONFIG_RESOURCE245(P, ...) RESOURCE P \
	CONFIG_RESOURCE244(__VA_ARGS__)
#define CONFIG_RESOURCE246(P, ...) RESOURCE P \
	CONFIG_RESOURCE245(__VA_ARGS__)
#define CONFIG_RESOURCE247(P, ...) RESOURCE P \
	CONFIG_RESOURCE246(__VA_ARGS__)
#define CONFIG_RESOURCE248(P, ...) RESOURCE P \
	CONFIG_RESOURCE247(__VA_ARGS__)
#define CONFIG_RESOURCE249(P, ...) RESOURCE P \
	CONFIG_RESOURCE248(__VA_ARGS__)
#define CONFIG_RESOURCE250(P, ...) RESOURCE P \
	CONFIG_RESOURCE249(__VA_ARGS__)
#define CONFIG_RESOURCE251(P, ...) RESOURCE P \
	CONFIG_RESOURCE250(__VA_ARGS__)
#define CONFIG_RESOURCE252(P, ...) RESOURCE P \
	CONFIG_RESOURCE251(__VA_ARGS__)
#define CONFIG_RESOURCE253(P, ...) RESOURCE P \
	CONFIG_RESOURCE252(__VA_ARGS__)
#define CONFIG_RESOURCE254(P, ...) RESOURCE P \
	CONFIG_RESOURCE253(__VA_ARGS__)
#define CONFIG_RESOURCE255(P, ...) RESOURCE P \
	CONFIG_RESOURCE254(__VA_ARGS__)
#define CONFIG_RESOURCE256(P, ...) RESOURCE P \
	CONFIG_RESOURCE255(__VA_ARGS__)

// The entry point into the iterative configuration class resource generation
#define CONFIG_RESOURCE_ITEMS(...) macro_dispatcher(CONFIG_RESOURCE, __VA_ARGS__) (__VA_ARGS__)

// Iterative Macros for generating the code to register the resources within the ConfigurationWrapper
#define CONFIG_WRAPPER_REGISTER1(P) CONFIG_WRAPPER_REGISTER_RESOURCE P
#define CONFIG_WRAPPER_REGISTER2(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER1(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER3(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER2(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER4(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER3(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER5(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER4(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER6(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER5(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER7(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER6(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER8(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER7(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER9(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER8(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER10(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER9(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER11(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER10(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER12(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER11(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER13(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER12(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER14(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER13(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER15(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER14(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER16(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER15(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER17(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER16(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER18(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER17(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER19(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER18(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER20(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER19(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER21(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER20(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER22(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER21(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER23(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER22(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER24(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER23(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER25(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER24(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER26(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER25(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER27(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER26(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER28(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER27(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER29(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER28(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER30(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER29(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER31(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER30(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER32(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER31(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER33(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER32(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER34(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER33(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER35(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER34(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER36(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER35(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER37(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER36(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER38(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER37(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER39(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER38(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER40(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER39(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER41(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER40(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER42(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER41(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER43(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER42(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER44(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER43(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER45(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER44(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER46(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER45(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER47(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER46(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER48(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER47(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER49(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER48(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER50(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER49(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER51(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER50(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER52(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER51(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER53(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER52(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER54(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER53(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER55(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER54(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER56(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER55(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER57(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER56(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER58(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER57(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER59(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER58(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER60(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER59(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER61(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER60(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER62(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER61(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER63(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER62(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER64(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER63(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER65(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER64(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER66(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER65(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER67(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER66(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER68(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER67(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER69(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER68(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER70(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER69(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER71(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER70(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER72(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER71(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER73(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER72(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER74(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER73(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER75(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER74(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER76(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER75(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER77(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER76(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER78(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER77(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER79(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER78(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER80(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER79(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER81(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER80(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER82(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER81(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER83(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER82(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER84(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER83(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER85(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER84(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER86(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER85(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER87(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER86(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER88(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER87(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER89(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER88(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER90(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER89(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER91(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER90(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER92(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER91(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER93(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER92(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER94(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER93(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER95(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER94(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER96(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER95(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER97(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER96(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER98(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER97(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER99(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER98(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER100(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER99(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER101(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER100(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER102(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER101(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER103(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER102(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER104(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER103(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER105(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER104(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER106(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER105(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER107(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER106(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER108(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER107(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER109(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER108(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER110(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER109(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER111(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER110(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER112(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER111(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER113(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER112(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER114(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER113(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER115(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER114(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER116(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER115(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER117(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER116(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER118(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER117(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER119(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER118(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER120(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER119(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER121(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER120(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER122(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER121(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER123(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER122(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER124(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER123(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER125(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER124(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER126(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER125(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER127(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER126(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER128(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER127(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER129(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER128(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER130(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER129(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER131(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER130(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER132(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER131(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER133(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER132(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER134(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER133(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER135(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER134(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER136(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER135(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER137(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER136(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER138(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER137(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER139(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER138(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER140(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER139(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER141(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER140(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER142(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER141(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER143(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER142(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER144(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER143(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER145(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER144(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER146(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER145(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER147(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER146(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER148(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER147(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER149(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER148(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER150(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER149(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER151(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER150(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER152(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER151(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER153(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER152(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER154(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER153(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER155(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER154(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER156(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER155(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER157(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER156(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER158(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER157(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER159(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER158(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER160(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER159(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER161(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER160(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER162(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER161(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER163(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER162(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER164(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER163(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER165(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER164(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER166(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER165(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER167(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER166(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER168(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER167(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER169(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER168(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER170(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER169(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER171(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER170(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER172(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER171(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER173(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER172(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER174(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER173(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER175(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER174(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER176(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER175(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER177(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER176(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER178(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER177(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER179(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER178(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER180(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER179(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER181(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER180(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER182(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER181(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER183(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER182(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER184(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER183(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER185(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER184(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER186(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER185(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER187(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER186(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER188(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER187(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER189(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER188(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER190(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER189(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER191(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER190(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER192(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER191(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER193(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER192(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER194(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER193(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER195(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER194(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER196(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER195(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER197(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER196(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER198(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER197(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER199(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER198(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER200(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER199(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER201(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER200(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER202(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER201(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER203(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER202(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER204(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER203(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER205(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER204(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER206(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER205(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER207(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER206(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER208(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER207(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER209(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER208(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER210(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER209(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER211(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER210(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER212(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER211(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER213(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER212(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER214(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER213(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER215(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER214(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER216(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER215(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER217(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER216(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER218(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER217(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER219(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER218(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER220(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER219(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER221(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER220(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER222(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER221(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER223(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER222(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER224(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER223(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER225(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER224(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER226(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER225(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER227(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER226(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER228(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER227(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER229(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER228(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER230(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER229(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER231(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER230(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER232(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER231(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER233(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER232(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER234(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER233(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER235(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER234(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER236(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER235(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER237(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER236(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER238(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER237(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER239(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER238(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER240(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER239(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER241(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER240(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER242(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER241(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER243(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER242(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER244(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER243(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER245(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER244(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER246(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER245(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER247(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER246(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER248(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER247(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER249(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER248(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER250(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER249(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER251(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER250(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER252(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER251(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER253(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER252(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER254(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER253(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER255(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER254(__VA_ARGS__)
#define CONFIG_WRAPPER_REGISTER256(P, ...) CONFIG_WRAPPER_REGISTER_RESOURCE P \
	CONFIG_WRAPPER_REGISTER255(__VA_ARGS__)

// The entry point into the iterative ConfigurationWrapper resource registration
#define CONFIG_WRAPPER_ITEMS(...) macro_dispatcher(CONFIG_WRAPPER_REGISTER, __VA_ARGS__) (__VA_ARGS__)

// Macro for generating the resources with the appropriate ConfigrationWrapper
#define RESOURCES(Config, ...) \
		private: \
			CONFIG_RESOURCE_ITEMS(__VA_ARGS__) \
}; \
CONFIGURATION_WRAPPER_REGISTER_RESOURCES_DECL(Config) \
	CONFIG_WRAPPER_ITEMS(__VA_ARGS__) \
}

// Macro for adding a single configuration dependency into the vector
#define ADD_CONFIG_DEP(Config) deps.push_back(new corm::ConfigurationWrapper<Config>(manager));

// Iterative macro to allow registering dependent configuration within a configuration
#define CONFIG_DEP1(Config, ...) ADD_CONFIG_DEP(Config)
#define CONFIG_DEP2(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP1(__VA_ARGS__)
#define CONFIG_DEP3(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP2(__VA_ARGS__)
#define CONFIG_DEP4(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP3(__VA_ARGS__)
#define CONFIG_DEP5(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP4(__VA_ARGS__)
#define CONFIG_DEP6(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP5(__VA_ARGS__)
#define CONFIG_DEP7(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP6(__VA_ARGS__)
#define CONFIG_DEP8(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP7(__VA_ARGS__)
#define CONFIG_DEP9(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP8(__VA_ARGS__)
#define CONFIG_DEP10(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP9(__VA_ARGS__)
#define CONFIG_DEP11(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP10(__VA_ARGS__)
#define CONFIG_DEP12(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP11(__VA_ARGS__)
#define CONFIG_DEP13(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP12(__VA_ARGS__)
#define CONFIG_DEP14(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP13(__VA_ARGS__)
#define CONFIG_DEP15(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP14(__VA_ARGS__)
#define CONFIG_DEP16(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP15(__VA_ARGS__)
#define CONFIG_DEP17(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP16(__VA_ARGS__)
#define CONFIG_DEP18(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP17(__VA_ARGS__)
#define CONFIG_DEP19(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP18(__VA_ARGS__)
#define CONFIG_DEP20(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP19(__VA_ARGS__)
#define CONFIG_DEP21(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP20(__VA_ARGS__)
#define CONFIG_DEP22(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP21(__VA_ARGS__)
#define CONFIG_DEP23(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP22(__VA_ARGS__)
#define CONFIG_DEP24(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP23(__VA_ARGS__)
#define CONFIG_DEP25(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP24(__VA_ARGS__)
#define CONFIG_DEP26(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP25(__VA_ARGS__)
#define CONFIG_DEP27(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP26(__VA_ARGS__)
#define CONFIG_DEP28(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP27(__VA_ARGS__)
#define CONFIG_DEP29(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP28(__VA_ARGS__)
#define CONFIG_DEP30(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP29(__VA_ARGS__)
#define CONFIG_DEP31(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP30(__VA_ARGS__)
#define CONFIG_DEP32(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP31(__VA_ARGS__)
#define CONFIG_DEP33(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP32(__VA_ARGS__)
#define CONFIG_DEP34(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP33(__VA_ARGS__)
#define CONFIG_DEP35(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP34(__VA_ARGS__)
#define CONFIG_DEP36(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP35(__VA_ARGS__)
#define CONFIG_DEP37(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP36(__VA_ARGS__)
#define CONFIG_DEP38(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP37(__VA_ARGS__)
#define CONFIG_DEP39(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP38(__VA_ARGS__)
#define CONFIG_DEP40(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP39(__VA_ARGS__)
#define CONFIG_DEP41(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP40(__VA_ARGS__)
#define CONFIG_DEP42(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP41(__VA_ARGS__)
#define CONFIG_DEP43(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP42(__VA_ARGS__)
#define CONFIG_DEP44(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP43(__VA_ARGS__)
#define CONFIG_DEP45(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP44(__VA_ARGS__)
#define CONFIG_DEP46(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP45(__VA_ARGS__)
#define CONFIG_DEP47(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP46(__VA_ARGS__)
#define CONFIG_DEP48(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP47(__VA_ARGS__)
#define CONFIG_DEP49(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP48(__VA_ARGS__)
#define CONFIG_DEP50(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP49(__VA_ARGS__)
#define CONFIG_DEP51(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP50(__VA_ARGS__)
#define CONFIG_DEP52(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP51(__VA_ARGS__)
#define CONFIG_DEP53(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP52(__VA_ARGS__)
#define CONFIG_DEP54(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP53(__VA_ARGS__)
#define CONFIG_DEP55(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP54(__VA_ARGS__)
#define CONFIG_DEP56(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP55(__VA_ARGS__)
#define CONFIG_DEP57(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP56(__VA_ARGS__)
#define CONFIG_DEP58(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP57(__VA_ARGS__)
#define CONFIG_DEP59(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP58(__VA_ARGS__)
#define CONFIG_DEP60(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP59(__VA_ARGS__)
#define CONFIG_DEP61(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP60(__VA_ARGS__)
#define CONFIG_DEP62(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP61(__VA_ARGS__)
#define CONFIG_DEP63(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP62(__VA_ARGS__)
#define CONFIG_DEP64(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP63(__VA_ARGS__)
#define CONFIG_DEP65(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP64(__VA_ARGS__)
#define CONFIG_DEP66(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP65(__VA_ARGS__)
#define CONFIG_DEP67(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP66(__VA_ARGS__)
#define CONFIG_DEP68(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP67(__VA_ARGS__)
#define CONFIG_DEP69(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP68(__VA_ARGS__)
#define CONFIG_DEP70(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP69(__VA_ARGS__)
#define CONFIG_DEP71(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP70(__VA_ARGS__)
#define CONFIG_DEP72(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP71(__VA_ARGS__)
#define CONFIG_DEP73(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP72(__VA_ARGS__)
#define CONFIG_DEP74(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP73(__VA_ARGS__)
#define CONFIG_DEP75(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP74(__VA_ARGS__)
#define CONFIG_DEP76(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP75(__VA_ARGS__)
#define CONFIG_DEP77(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP76(__VA_ARGS__)
#define CONFIG_DEP78(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP77(__VA_ARGS__)
#define CONFIG_DEP79(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP78(__VA_ARGS__)
#define CONFIG_DEP80(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP79(__VA_ARGS__)
#define CONFIG_DEP81(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP80(__VA_ARGS__)
#define CONFIG_DEP82(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP81(__VA_ARGS__)
#define CONFIG_DEP83(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP82(__VA_ARGS__)
#define CONFIG_DEP84(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP83(__VA_ARGS__)
#define CONFIG_DEP85(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP84(__VA_ARGS__)
#define CONFIG_DEP86(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP85(__VA_ARGS__)
#define CONFIG_DEP87(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP86(__VA_ARGS__)
#define CONFIG_DEP88(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP87(__VA_ARGS__)
#define CONFIG_DEP89(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP88(__VA_ARGS__)
#define CONFIG_DEP90(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP89(__VA_ARGS__)
#define CONFIG_DEP91(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP90(__VA_ARGS__)
#define CONFIG_DEP92(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP91(__VA_ARGS__)
#define CONFIG_DEP93(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP92(__VA_ARGS__)
#define CONFIG_DEP94(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP93(__VA_ARGS__)
#define CONFIG_DEP95(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP94(__VA_ARGS__)
#define CONFIG_DEP96(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP95(__VA_ARGS__)
#define CONFIG_DEP97(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP96(__VA_ARGS__)
#define CONFIG_DEP98(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP97(__VA_ARGS__)
#define CONFIG_DEP99(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP98(__VA_ARGS__)
#define CONFIG_DEP100(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP99(__VA_ARGS__)
#define CONFIG_DEP101(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP100(__VA_ARGS__)
#define CONFIG_DEP102(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP101(__VA_ARGS__)
#define CONFIG_DEP103(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP102(__VA_ARGS__)
#define CONFIG_DEP104(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP103(__VA_ARGS__)
#define CONFIG_DEP105(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP104(__VA_ARGS__)
#define CONFIG_DEP106(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP105(__VA_ARGS__)
#define CONFIG_DEP107(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP106(__VA_ARGS__)
#define CONFIG_DEP108(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP107(__VA_ARGS__)
#define CONFIG_DEP109(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP108(__VA_ARGS__)
#define CONFIG_DEP110(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP109(__VA_ARGS__)
#define CONFIG_DEP111(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP110(__VA_ARGS__)
#define CONFIG_DEP112(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP111(__VA_ARGS__)
#define CONFIG_DEP113(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP112(__VA_ARGS__)
#define CONFIG_DEP114(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP113(__VA_ARGS__)
#define CONFIG_DEP115(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP114(__VA_ARGS__)
#define CONFIG_DEP116(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP115(__VA_ARGS__)
#define CONFIG_DEP117(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP116(__VA_ARGS__)
#define CONFIG_DEP118(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP117(__VA_ARGS__)
#define CONFIG_DEP119(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP118(__VA_ARGS__)
#define CONFIG_DEP120(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP119(__VA_ARGS__)
#define CONFIG_DEP121(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP120(__VA_ARGS__)
#define CONFIG_DEP122(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP121(__VA_ARGS__)
#define CONFIG_DEP123(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP122(__VA_ARGS__)
#define CONFIG_DEP124(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP123(__VA_ARGS__)
#define CONFIG_DEP125(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP124(__VA_ARGS__)
#define CONFIG_DEP126(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP125(__VA_ARGS__)
#define CONFIG_DEP127(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP126(__VA_ARGS__)
#define CONFIG_DEP128(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP127(__VA_ARGS__)
#define CONFIG_DEP129(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP128(__VA_ARGS__)
#define CONFIG_DEP130(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP129(__VA_ARGS__)
#define CONFIG_DEP131(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP130(__VA_ARGS__)
#define CONFIG_DEP132(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP131(__VA_ARGS__)
#define CONFIG_DEP133(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP132(__VA_ARGS__)
#define CONFIG_DEP134(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP133(__VA_ARGS__)
#define CONFIG_DEP135(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP134(__VA_ARGS__)
#define CONFIG_DEP136(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP135(__VA_ARGS__)
#define CONFIG_DEP137(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP136(__VA_ARGS__)
#define CONFIG_DEP138(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP137(__VA_ARGS__)
#define CONFIG_DEP139(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP138(__VA_ARGS__)
#define CONFIG_DEP140(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP139(__VA_ARGS__)
#define CONFIG_DEP141(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP140(__VA_ARGS__)
#define CONFIG_DEP142(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP141(__VA_ARGS__)
#define CONFIG_DEP143(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP142(__VA_ARGS__)
#define CONFIG_DEP144(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP143(__VA_ARGS__)
#define CONFIG_DEP145(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP144(__VA_ARGS__)
#define CONFIG_DEP146(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP145(__VA_ARGS__)
#define CONFIG_DEP147(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP146(__VA_ARGS__)
#define CONFIG_DEP148(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP147(__VA_ARGS__)
#define CONFIG_DEP149(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP148(__VA_ARGS__)
#define CONFIG_DEP150(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP149(__VA_ARGS__)
#define CONFIG_DEP151(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP150(__VA_ARGS__)
#define CONFIG_DEP152(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP151(__VA_ARGS__)
#define CONFIG_DEP153(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP152(__VA_ARGS__)
#define CONFIG_DEP154(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP153(__VA_ARGS__)
#define CONFIG_DEP155(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP154(__VA_ARGS__)
#define CONFIG_DEP156(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP155(__VA_ARGS__)
#define CONFIG_DEP157(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP156(__VA_ARGS__)
#define CONFIG_DEP158(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP157(__VA_ARGS__)
#define CONFIG_DEP159(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP158(__VA_ARGS__)
#define CONFIG_DEP160(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP159(__VA_ARGS__)
#define CONFIG_DEP161(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP160(__VA_ARGS__)
#define CONFIG_DEP162(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP161(__VA_ARGS__)
#define CONFIG_DEP163(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP162(__VA_ARGS__)
#define CONFIG_DEP164(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP163(__VA_ARGS__)
#define CONFIG_DEP165(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP164(__VA_ARGS__)
#define CONFIG_DEP166(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP165(__VA_ARGS__)
#define CONFIG_DEP167(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP166(__VA_ARGS__)
#define CONFIG_DEP168(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP167(__VA_ARGS__)
#define CONFIG_DEP169(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP168(__VA_ARGS__)
#define CONFIG_DEP170(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP169(__VA_ARGS__)
#define CONFIG_DEP171(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP170(__VA_ARGS__)
#define CONFIG_DEP172(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP171(__VA_ARGS__)
#define CONFIG_DEP173(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP172(__VA_ARGS__)
#define CONFIG_DEP174(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP173(__VA_ARGS__)
#define CONFIG_DEP175(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP174(__VA_ARGS__)
#define CONFIG_DEP176(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP175(__VA_ARGS__)
#define CONFIG_DEP177(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP176(__VA_ARGS__)
#define CONFIG_DEP178(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP177(__VA_ARGS__)
#define CONFIG_DEP179(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP178(__VA_ARGS__)
#define CONFIG_DEP180(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP179(__VA_ARGS__)
#define CONFIG_DEP181(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP180(__VA_ARGS__)
#define CONFIG_DEP182(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP181(__VA_ARGS__)
#define CONFIG_DEP183(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP182(__VA_ARGS__)
#define CONFIG_DEP184(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP183(__VA_ARGS__)
#define CONFIG_DEP185(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP184(__VA_ARGS__)
#define CONFIG_DEP186(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP185(__VA_ARGS__)
#define CONFIG_DEP187(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP186(__VA_ARGS__)
#define CONFIG_DEP188(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP187(__VA_ARGS__)
#define CONFIG_DEP189(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP188(__VA_ARGS__)
#define CONFIG_DEP190(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP189(__VA_ARGS__)
#define CONFIG_DEP191(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP190(__VA_ARGS__)
#define CONFIG_DEP192(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP191(__VA_ARGS__)
#define CONFIG_DEP193(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP192(__VA_ARGS__)
#define CONFIG_DEP194(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP193(__VA_ARGS__)
#define CONFIG_DEP195(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP194(__VA_ARGS__)
#define CONFIG_DEP196(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP195(__VA_ARGS__)
#define CONFIG_DEP197(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP196(__VA_ARGS__)
#define CONFIG_DEP198(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP197(__VA_ARGS__)
#define CONFIG_DEP199(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP198(__VA_ARGS__)
#define CONFIG_DEP200(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP199(__VA_ARGS__)
#define CONFIG_DEP201(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP200(__VA_ARGS__)
#define CONFIG_DEP202(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP201(__VA_ARGS__)
#define CONFIG_DEP203(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP202(__VA_ARGS__)
#define CONFIG_DEP204(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP203(__VA_ARGS__)
#define CONFIG_DEP205(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP204(__VA_ARGS__)
#define CONFIG_DEP206(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP205(__VA_ARGS__)
#define CONFIG_DEP207(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP206(__VA_ARGS__)
#define CONFIG_DEP208(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP207(__VA_ARGS__)
#define CONFIG_DEP209(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP208(__VA_ARGS__)
#define CONFIG_DEP210(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP209(__VA_ARGS__)
#define CONFIG_DEP211(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP210(__VA_ARGS__)
#define CONFIG_DEP212(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP211(__VA_ARGS__)
#define CONFIG_DEP213(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP212(__VA_ARGS__)
#define CONFIG_DEP214(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP213(__VA_ARGS__)
#define CONFIG_DEP215(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP214(__VA_ARGS__)
#define CONFIG_DEP216(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP215(__VA_ARGS__)
#define CONFIG_DEP217(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP216(__VA_ARGS__)
#define CONFIG_DEP218(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP217(__VA_ARGS__)
#define CONFIG_DEP219(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP218(__VA_ARGS__)
#define CONFIG_DEP220(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP219(__VA_ARGS__)
#define CONFIG_DEP221(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP220(__VA_ARGS__)
#define CONFIG_DEP222(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP221(__VA_ARGS__)
#define CONFIG_DEP223(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP222(__VA_ARGS__)
#define CONFIG_DEP224(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP223(__VA_ARGS__)
#define CONFIG_DEP225(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP224(__VA_ARGS__)
#define CONFIG_DEP226(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP225(__VA_ARGS__)
#define CONFIG_DEP227(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP226(__VA_ARGS__)
#define CONFIG_DEP228(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP227(__VA_ARGS__)
#define CONFIG_DEP229(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP228(__VA_ARGS__)
#define CONFIG_DEP230(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP229(__VA_ARGS__)
#define CONFIG_DEP231(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP230(__VA_ARGS__)
#define CONFIG_DEP232(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP231(__VA_ARGS__)
#define CONFIG_DEP233(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP232(__VA_ARGS__)
#define CONFIG_DEP234(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP233(__VA_ARGS__)
#define CONFIG_DEP235(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP234(__VA_ARGS__)
#define CONFIG_DEP236(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP235(__VA_ARGS__)
#define CONFIG_DEP237(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP236(__VA_ARGS__)
#define CONFIG_DEP238(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP237(__VA_ARGS__)
#define CONFIG_DEP239(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP238(__VA_ARGS__)
#define CONFIG_DEP240(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP239(__VA_ARGS__)
#define CONFIG_DEP241(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP240(__VA_ARGS__)
#define CONFIG_DEP242(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP241(__VA_ARGS__)
#define CONFIG_DEP243(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP242(__VA_ARGS__)
#define CONFIG_DEP244(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP243(__VA_ARGS__)
#define CONFIG_DEP245(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP244(__VA_ARGS__)
#define CONFIG_DEP246(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP245(__VA_ARGS__)
#define CONFIG_DEP247(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP246(__VA_ARGS__)
#define CONFIG_DEP248(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP247(__VA_ARGS__)
#define CONFIG_DEP249(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP248(__VA_ARGS__)
#define CONFIG_DEP250(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP249(__VA_ARGS__)
#define CONFIG_DEP251(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP250(__VA_ARGS__)
#define CONFIG_DEP252(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP251(__VA_ARGS__)
#define CONFIG_DEP253(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP252(__VA_ARGS__)
#define CONFIG_DEP254(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP253(__VA_ARGS__)
#define CONFIG_DEP255(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP254(__VA_ARGS__)
#define CONFIG_DEP256(Config, ...) ADD_CONFIG_DEP(Config) \
		CONFIG_DEP255(__VA_ARGS__)

// Entry point for generating config depedencies
#define CONFIG_DEP_ITEMS(...) macro_dispatcher(CONFIG_DEP, __VA_ARGS__) (__VA_ARGS__)

// Add dependency configurations
#define DEPENDENCIES(...) \
	static std::vector<corm::ConfigurationWrapperInterface*> getDependentConfigurations(corm::BeanManager* manager) { \
		std::vector<corm::ConfigurationWrapperInterface*> deps; \
		CONFIG_DEP_ITEMS(__VA_ARGS__) \
		return deps; \
	}

#endif /* CONFIGURATIONMACRO_H_ */
